import {useState} from 'react';
import {Link} from 'react-router-dom';
import Eye from 'lucide-react/dist/esm/icons/eye.js';
import EyeOff from 'lucide-react/dist/esm/icons/eye-off.js';
import {useRegister} from '../shared/hooks/useRegister.jsx';
import {Input,Button,IconButton} from './ui/index.jsx';
export function Register() {
 const {registerUser,isLoading} = useRegister(),[show,setShow] = useState(false),[password,setPassword] = useState(''),[error,setError] = useState('');
 const rules = [password.length >= 8,/[a-z]/.test(password),/[A-Z]/.test(password),/[0-9]/.test(password),/[^a-zA-Z0-9]/.test(password)],strength = rules.filter(Boolean).length;
 const submit = event => {event.preventDefault(); const data = new FormData(event.currentTarget); if (strength < 5) return setError('Usa al menos 8 caracteres, mayúscula, minúscula, número y símbolo'); if (data.get('confirm') !== password) return setError('Las contraseñas no coinciden'); setError(''); registerUser({username:data.get('username'),email:data.get('email'),password});};
 return <div className="auth-card card"><span className="eyebrow">TU VOZ EMPIEZA AQUÍ</span><h1>Elige cómo te conocen.</h1><p>No pedimos tu nombre. Usa un alias que no te identifique.</p><form onSubmit={submit} className="stack"><Input label="Alias" name="username" autoComplete="username" pattern="[a-zA-Z0-9_]{3,20}" minLength={3} maxLength={20} required/><Input label="Correo privado" name="email" type="email" autoComplete="email" maxLength={254} required/><div className="password-field"><Input label="Contraseña" type={show ? 'text':'password'} autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} minLength={8} maxLength={128} required/><IconButton label={show ? 'Ocultar contraseña':'Mostrar contraseña'} onClick={() => setShow(!show)}>{show ? <EyeOff size={18}/>:<Eye size={18}/>}</IconButton></div><meter min="0" max="5" value={strength} aria-label="Seguridad de contraseña"/><small>8–128 caracteres: mayúscula, minúscula, número y símbolo.</small><Input label="Repite la contraseña" name="confirm" type={show ? 'text':'password'} autoComplete="new-password" maxLength={128} required/>{error && <p role="alert" className="error-text">{error}</p>}<Button type="submit" disabled={isLoading}>{isLoading ? 'Creando…':'Crear mi cuenta'}</Button></form><small>Guardamos el correo para iniciar sesión y enviarte una bienvenida. Puedes añadir una foto después, desde ajustes.</small><p>¿Ya tienes cuenta? <Link to="/auth">Inicia sesión</Link></p></div>;
}
